name: Deploy to NAS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        if [ -f package.json ]; then
          npm ci
        else
          echo "No package.json found, skipping npm install"
        fi
    
    - name: Build React app
      run: |
        if [ -f package.json ]; then
          npm run build
        else
          echo "No package.json found, skipping build"
        fi
    
    - name: Build Docker image
      run: |
        docker build -t ${{ github.repository }}:${{ github.sha }} .
        docker tag ${{ github.repository }}:${{ github.sha }} ${{ github.repository }}:latest
    
    - name: Save Docker image
      run: |
        docker save ${{ github.repository }}:latest > app.tar
    
    - name: Deploy to NAS
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Ready to deploy to NAS"
        echo "Image saved as app.tar"
        # 这里可以添加实际的 NAS 部署脚本
        # 例如: scp app.tar user@nas-ip:/path/to/deploy/
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: app.tar
